name: Package

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Environments
        run: |
          echo "SM_VERSION=1.11" >> $GITHUB_ENV
          echo "PLUGIN_VERSION_REVISION<<EOF" >> $GITHUB_ENV
          git rev-list --count HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      
      - name: Install
        run: |
          bash scripts/install.sh
      
      - name: Set Version
        run: |
          bash scripts/version.sh
      
      - name: Compile
        run: |
          cd build/addons/sourcemod/scripting
          ./spcomp superzombiefortress.sp -o ../plugins/superzombiefortress.smx
      
      - name: Package
        run: |
          bash scripts/package.sh
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: SuperZombieFortress-${{env.PLUGIN_VERSION}}.${{env.PLUGIN_VERSION_REVISION}}
          path: ./build/package